name: Sync Template Updates

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout template repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false 
          fetch-depth: 0

      - name: Setup Git user
        run: |
          git config --global user.name "GitHub Sync Bot"
          git config --global user.email "actions@github.com"

      - name: Push to emailmanager-6
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git remote add target https://x-access-token:${TOKEN}@github.com/controller007/emailmanager-6.git
          git push target main --force

      - name: Push to emailmanager-5
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git remote add target2 https://x-access-token:${TOKEN}@github.com/controller007/emailmanager-5.git
          git push target2 main --force

      - name: Push to emailanager-4
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git remote add target3 https://x-access-token:${TOKEN}@github.com/controller007/emailanager-4.git
          git push target3 main --force

      - name: Push to emailanager-3
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git remote add target4 https://x-access-token:${TOKEN}@github.com/controller007/emailanager-3.git
          git push target4 main --force

      - name: Push to emailanager-1
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git remote add target5 https://x-access-token:${TOKEN}@github.com/controller007/emailmanager.git
          git push target5 main --force